#!/bin/bash
# ------------------------------------------------------------------------------
# 
# Name: battery
# Author: Gabe Gonzalez
# 
# Brief: Display battery information.
# 
# ------------------------------------------------------------------------------

##
# Project name.
##
PROJECT="${0##*/}"

##
# Files/directories.
##
BATTERY_DIR="/sys/class/power_supply/BAT0"

##
# Options.
##
INFO=
SHORT=

##
# Exit statuses.
##
EXIT_BATTERY_NOT_PRESENT=11

##
# Main.
##
main()
{
    if [ $# -eq 0 ]
    then
        battery_print_charge
        return $?
    fi

    # Parse options
    local short="his"
    local long="help,info,short"
    local args=$(getopt -o "${short}" --long "${long}" --name "${PROJECT}" \
                        -- "${@}")
    if [ $? -ne 0 ]
    then
        usage
        exit 1
    fi
    eval set -- "${args}"

    while true
    do
        case "${1}" in
            -h|--help)
                usage
                return 0
                ;;
            -i|--info)
                INFO=true
                ;;
            -s|--short)
                SHORT=true
                ;;
            *)
                break
                ;;
        esac
        shift
    done

    # Run checks
    if ! battery_is_present
    then
        echo "${PROJECT}: Battery not present." 1>&2
        return ${EXIT_BATTERY_NOT_PRESENT}
    fi

    # Run specified option
    battery_print_charge
    if [ -n "${INFO}" ]
    then
        battery_print_info 
    fi

    return $?
}

##
# Print program usage.
##
usage()
{
    echo "Usage: ${PROJECT} [options]"
    echo
    echo "Options:"
    echo "    -h, --help"
    echo "        Print program usage message."
    echo 
    echo "    -i, --info"
    echo "        Print extra battery information."
    echo 
    echo "    -s, --short"
    echo "        Shorten printed output."
}

##
# Print current battery charge.
##
battery_print_charge()
{
    local batnow=$(battery_get_charge)
    local batfull=$(battery_get_charge_full)
    local batstatus=$(battery_get_status)
    local charge=$(echo "scale=3; ${batnow} / ${batfull} * 100" \
                       | bc \
                       | sed 's/..$//')
    local msg="${charge}% (${batstatus})"
    if [ -n "${SHORT}" ]
    then
        echo "${msg}"
    else
        echo "Battery: ${msg}"
    fi
}

##
# Print extra battery information.
##
battery_print_info()
{
    local batfulldesign=$(battery_get_charge_full_design | sed 's/...$//')
    local batfull=$(battery_get_charge_full | sed 's/...$//')
    local battech=$(battery_get_technology)
    local capacity=$(echo "scale=3; ${batfull} / ${batfulldesign} * 100" \
        | bc \
        | sed 's/..$//')
    echo "* ${battech} battery"
    echo "* Design capacity ${batfulldesign} mAh"
    echo "* Current capacity ${batfull} mAh (${capacity}% of design)"
}

##
# Return the current battery charge.
##
battery_get_charge()
{
    local file="${BATTERY_DIR}/charge_now"
    local line=
    read -r line < "${file}"
    echo "${line}"
}

##
# Return the battery charge when battery is full.
##
battery_get_charge_full()
{
    local file="${BATTERY_DIR}/charge_full"
    local line=
    read -r line < "${file}"
    echo "${line}"
}

##
# Return the battery charge when battery is full, as it was designed.
##
battery_get_charge_full_design()
{
    local file="${BATTERY_DIR}/charge_full_design"
    local line=
    read -r line < "${file}"
    echo "${line}"
}

##
# Return the current battery status.
##
battery_get_status()
{
    local file="${BATTERY_DIR}/status"
    local line=
    read -r line < "${file}"
    echo "${line}"
}

##
# Return the battery technology.
##
battery_get_technology()
{
    local file="${BATTERY_DIR}/technology"
    local line=
    read -r line < "${file}"
    echo "${line}"
}

##
# Check if the battery is present.
##
battery_is_present()
{
    local file="${BATTERY_DIR}/present"
    local status=
    read -r status < "${file}"
    if [ ${status} -eq 1 ]
    then
        return 0
    fi
    return 1
}

##
# Run script.
##
main "${@}"
